replicaCount: 2

image:
  repository: artifactory.zenforcode.com/keyfort
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: fastapi.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

