# foundationdb.conf
plugin_version = 2
[fdbmonitor]
user = root
[general]
restart_delay = 60
cluster_file = /etc/foundationdb/fdb.cluster

[foundationdb]
# Use the container hostname as the coordinator
coordination_class = ssd
datadir = /var/lib/foundationdb/data
logdir = /var/log/foundationdb
