name: Pull Request Build Check

on:
  pull_request:
    branches:
      - '**' # Triggers on all branches (customize as needed)
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Configure Go environment
        run: |
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "GOBIN=$HOME/go/bin" >> $GITHUB_ENV
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install Node dependencies
        run: |
          npm install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Export OpenAPI spec and generate SDK
        run: |
          uv run extract-openapi.py
          npm run fern:init
          npm run fern:all
          npm run fern:gen

      - name: Run test and build (Go)
        run: |
          make build
