name: Pull Request Build Check
on:
  pull_request:
    branches:
      - '**' # Triggers on all branches (customize as needed)
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Build the code.
        run: |
<<<<<<< Updated upstream
          make build
    
=======
          npm install

      - name: Export OpenAPI spec and generate SDK.
        run: |
          uv run extract-openapi.py
          npm run fern:init
          npm run fern:all
          npm run fern:gen

      - name: Extract semver version.
        run: |
          ver=$(uv run dunamai from git --no-metadata --format "{base}-{commit}")
          echo "VERSION=${ver}" >> $GITHUB_ENV

      - name: Build Docker image.
        run: |
          echo "${{ env.VERSION }}"
          docker build . -t artifactory.keyfort.zenforcode.com:latest
>>>>>>> Stashed changes
