name: Workflow Dispatch with Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (e.g., 1.0.0)
        required: true
        default: 1.0.0
jobs:
  versioning:
    permissions:
      contents: write  
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate version
        run: |
          VERSION="v${{ github.event.inputs.version }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Validating version: v${{ env.VERSION }}"

          if [[ ! "${{ env.VERSION }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Expected format: X.Y.Z (e.g., 1.0.0)"
            exit 1
          fi
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create and Push Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Tagging version: $env.VERSION"
          git tag -a "$VERSION" -m "Release $env.VERSION"
          git push origin "$env.VERSION"
          
